### ISSUE TITLE
Please allow right clicking into the input box.

### ISSUE THREAD

**Issue by amynbe** [iriiiina/JIRA-Issue-Opener-FF#4]
Hello,

it would be nice to be able to paste a jira key using the mouse and either have a paste-and-go option or a button to open the Jira issue without hitting enter.

Thanks,

**Comment by iriiiina** [comment]
Hi,
Thanks for your suggestions!
I will not add button, because it violates the idea of simplicity of this extensions, but I'll try to add cut/copy/paste/paste-and-go functionality on mouse right click (FireFox disables it by default).

Links for me:
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/ContextMenus
https://developer.mozilla.org/en-US/docs/Web/Events/contextmenu?redirectlocale=en-US&redirectslug=DOM%2FMozilla_event_reference%2Fcontextmenu
